import EditorData from '../../EditorData';

const rw3: EditorData = {
	platforms: [
		{
			h: 440,
			a: 0,
			w: 20,
			th: 32,
			motion: 0,
			material: 'gthin',
			ceiling: false,
			walls: false,
		},
		{
			h: 440,
			a: 270,
			w: 20,
			th: 32,
			motion: 0,
			material: 'gthin',
			ceiling: false,
			walls: false,
		},
		{
			h: 440,
			a: 90,
			w: 20,
			th: 32,
			motion: 0,
			material: 'gthin',
			ceiling: false,
			walls: false,
		},
		{
			h: 440,
			a: 180,
			w: 20,
			th: 32,
			motion: 0,
			material: 'gthin',
		},
		{
			h: 560,
			a: 225,
			w: 20,
			th: 32,
			motion: 0,
			material: 'gsolid',
			walls: true,
			ceiling: true,
		},
		{
			h: 560,
			a: 135,
			w: 20,
			th: 32,
			motion: 0,
			material: 'gsolid',
			ceiling: true,
			walls: true,
		},
		{
			h: 560,
			a: 315,
			w: 20,
			th: 32,
			motion: 0,
			material: 'gsolid',
			walls: true,
			ceiling: true,
		},
		{
			h: 560,
			a: 45,
			w: 20,
			th: 32,
			motion: 0,
			material: 'gsolid',
			ceiling: true,
			walls: true,
		},
	],
	floors: [{ h: 320, a: 0, w: 360, material: 'gsolid' }],
	player: {
		type: 'woody',
		a: 180,
		r: 440,
		item: 'rock',
		weapon: 'axe',
	},
	enemies: [
		{ type: 'buster', a: 215, r: 320, dir: 'L' },
		{ type: 'buster', a: 135, r: 320, dir: 'L' },
		{ type: 'buster', a: 315, r: 320, dir: 'L' },
		{ type: 'krillna', a: 225, r: 560, dir: 'R' },
		{ type: 'krillna', a: 45, r: 560, dir: 'R' },
		{ type: 'krillna', a: 135, r: 560, dir: 'L' },
		{ type: 'krillna', a: 315, r: 560, dir: 'L' },
		{ type: 'buster', a: 45, r: 320, dir: 'L' },
		{ type: 'buster', a: 0, r: 440, dir: 'L' },
		{ type: 'buster', a: 90, r: 440, dir: 'L' },
		{ type: 'buster', a: 270, r: 440, dir: 'L' },
	],
};
export default rw3;
