import EditorData from '../../EditorData';

const rw4: EditorData = {
	platforms: [
		{
			h: 460,
			a: 180,
			w: 45,
			th: 32,
			motion: 2,
			material: 'gthin',
		},
		{
			h: 460,
			a: 0,
			w: 120,
			th: 32,
			motion: 2,
			material: 'gthin',
		},
		{
			h: 640,
			a: 180,
			w: 20,
			th: 32,
			motion: 0,
			material: 'gsolid',
			ceiling: true,
			walls: true,
		},
		{
			h: 640,
			a: 270,
			w: 20,
			th: 32,
			motion: 0,
			material: 'gsolid',
			ceiling: true,
			walls: true,
		},
		{
			h: 640,
			a: 90,
			w: 20,
			th: 32,
			motion: 0,
			material: 'gsolid',
			walls: true,
			ceiling: true,
		},
		{
			h: 640,
			a: 0,
			w: 20,
			th: 32,
			motion: 0,
			material: 'gsolid',
			ceiling: true,
			walls: true,
		},
	],
	walls: [],
	floors: [{ h: 240, a: 0, w: 360, material: 'gsolid' }],
	objects: [],
	player: {
		type: 'jacques',
		a: 180,
		r: 640,
		item: 'rock',
		weapon: 'axe',
	},
	enemies: [
		{ type: 'krillna', a: 270, r: 240, dir: 'R' },
		{ type: 'krillna', a: 45, r: 240, dir: 'R' },
		{ type: 'krillna', a: 135, r: 240, dir: 'R' },
		{ type: 'bat', a: 270, r: 300, dir: 'R' },
		{ type: 'bat', a: 90, r: 420, dir: 'L' },
	],
};
export default rw4;
