import { AnimName } from './flavours';

export const aStand: AnimName = 'stand',
	aFlip: AnimName = 'flip',
	aJumpFlip: AnimName = 'jflip',
	aDoubleJumpFlip: AnimName = 'djflip',
	aBackgroundLeapFlip: AnimName = 'blflip',
	aForegroundLeapFlip: AnimName = 'flflip',
	aWalk: AnimName = 'walk',
	aJump: AnimName = 'jump',
	aDoubleJump: AnimName = 'djump',
	aLand: AnimName = 'land',
	aThrow: AnimName = 'throw',
	aAxe: AnimName = 'axe',
	aHurt: AnimName = 'hurt',
	aStatus: AnimName = 'status',
	aDying: AnimName = 'dying',
	aForegroundAttack: AnimName = 'fattack',
	aSideAttack: AnimName = 'sattack',
	aBackgroundAttack: AnimName = 'battack',
	aBackgroundLeap: AnimName = 'bleap',
	aForegroundLeap: AnimName = 'fleap';
