export const eAnimationEnded = 'onanimend',
	eGameEnter = 'enter.level.isole',
	eGameMap = 'show.map.isole',
	eGameReady = 'ready.isole',
	ePlayerDied = 'died.player.isole',
	ePlayerDying = 'dying.player.isole',
	ePlayerHurt = 'hurt.player.isole',
	eThrow = 'onthrow',
	eSwing = 'onswing';
