export const zBackground = 0,
	zBackground1 = 1,
	zBackground2 = 2,
	zBackground3 = 3,
	zBackground4 = 4,
	zStructure = 11,
	zEnemy = 12,
	zPlayer = 13,
	zDecal = 14,
	zFlying = 15,
	zSpark = 16,
	zUI = 100,
	zBeforeUI = zUI - 1,
	zFirst = -1;

export default {
	Bg0: zBackground,
	Bg1: zBackground1,
	Bg2: zBackground2,
	Bg3: zBackground3,
	Bg4: zBackground4,
	Structure: zStructure,
	Enemy: zEnemy,
	Player: zPlayer,
	Decal: zDecal,
	Flying: zFlying,
	Spark: zSpark,
	UI: zUI,
};
